# Set the port
server.port=8081

# Save the database to a physical folder named "data" in your project
spring.datasource.url=jdbc:h2:file:./data/vobedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Tell Hibernate to UPDATE the tables, not overwrite them
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enable the web console
spring.h2.console.enabled=true