server.port=8081
# Give your app a name
spring.application.name=tracker

# Enable the H2 Console so we can see the DB in our browser
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Database Connection Settings
spring.datasource.url=jdbc:h2:mem:vobedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Show the SQL in the console so we can see what's happening
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update